# Generated by Django 3.2 on 2021-04-21 14:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('username', models.CharField(error_messages={'max_length': 'Le username est trop long'}, max_length=20, unique=True)),
                ('nom', models.CharField(error_messages={'max_length': 'Le nom est trop long'}, max_length=50, null=True)),
                ('prenom', models.CharField(error_messages={'max_length': 'Le prenom est trop long'}, max_length=50, null=True)),
                ('departement', models.CharField(blank=True, error_messages={'max_length': 'Le nom du département est trop long'}, max_length=50, null=True)),
                ('numtel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('photo', models.ImageField(null=True, upload_to='static/Photo_auditeur')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Administrateur'), (2, 'Auditeur')], default=2, null=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/Photo_responsable')),
                ('nom', models.CharField(error_messages={'max_length': 'Le nom est trop long'}, max_length=50)),
                ('prenom', models.CharField(error_messages={'max_length': 'Le prenom est trop long'}, max_length=50)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('numeroTel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='audits.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tauxRespect', models.IntegerField(blank=True)),
                ('tauxMin', models.IntegerField(blank=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='audits.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('photoStandard', models.CharField(max_length=100)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('valstandard', models.IntegerField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorie', to='audits.categorie')),
                ('zone', models.ManyToManyField(to='audits.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='audits.audit')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='audits.audit')),
                ('valeur', models.IntegerField(blank=True)),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audits.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.TextField(blank=True)),
                ('cause', models.TextField(blank=True)),
                ('actionAfaire', models.TextField(blank=True)),
                ('delai', models.DateTimeField()),
                ('tauxEfficacite', models.IntegerField(blank=True)),
                ('planAction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='audits.planaction')),
            ],
        ),
    ]
