# Generated by Django 3.2 on 2021-04-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('photoStandard', models.CharField(max_length=100)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('valstandard', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='date_de_creation',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='photoStandard',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='valstandard',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='zone',
        ),
        migrations.AlterField(
            model_name='standard',
            name='nom',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.AddField(
            model_name='critere',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Standard', to='audits.standard'),
        ),
        migrations.AddField(
            model_name='critere',
            name='zone',
            field=models.ManyToManyField(to='audits.Zone'),
        ),
    ]
