# Generated by Django 3.2 on 2021-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auto_20210423_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critere',
            name='nom',
        ),
        migrations.AlterField(
            model_name='critere',
            name='photoStandard',
            field=models.ImageField(blank=True, null=True, upload_to='static/Photo_critère'),
        ),
    ]
