# Generated by Django 3.2 on 2021-04-23 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20210423_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='valcritère',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='tauxEfficacite',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='audit',
            name='tauxMin',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='audit',
            name='tauxRespect',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
