# Generated by Django 3.2 on 2021-04-25 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_auto_20210423_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='valcritère',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='nom',
        ),
        migrations.AddField(
            model_name='standard',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='photoStandard',
            field=models.ImageField(blank=True, null=True, upload_to='static/Photo_critère'),
        ),
        migrations.AddField(
            model_name='standard',
            name='valstandard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='zone',
            field=models.ManyToManyField(to='audits.Zone'),
        ),
        migrations.DeleteModel(
            name='Critere',
        ),
        migrations.AddField(
            model_name='standard',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Categorie', to='audits.categorie'),
            preserve_default=False,
        ),
    ]
