# Generated by Django 3.2 on 2021-04-25 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_auto_20210425_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='tauxRespect',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
