# Generated by Django 3.2 on 2021-05-03 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_alter_action_tauxefficacite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='delai',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='tauxMin',
            field=models.IntegerField(blank=True, default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='valeur',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
