# Generated by Django 3.2 on 2021-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_auto_20210503_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='auditeur',
            field=models.CharField(choices=[('chef2', 'chef2'), ('chef1', 'chef1'), ('chef4', 'chef4'), ('chef3', 'chef3')], max_length=20, null=True, unique=True),
        ),
    ]
